[package]
name = "funboy-matrix"
version = "0.1.0"
edition = "2024"

[dependencies]
ollama-rs.workspace = true
reqwest.workspace = true
fsl-core.workspace = true
dotenvy = "0.15.7"
matrix-sdk = { version = "0.16.0", features = ["markdown"] }
funboy-core = { path = "../funboy-core" }
funboy-cli = { path = "../funboy-cli" }
sqlx = {version = "0.9.0-alpha.1", default-features = false, features = ["postgres", "runtime-tokio", "tls-rustls", "macros", "migrate"]}
tokio = {version = "1.39.2", features = ["full"]}
rand = "0.9.2"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.132"
async-recursion = "1.1.1"
tracing-subscriber = "0.3.23"
clap = "4.6.0"
mime = "0.3.17"
url = "2.5.8"

