[package]
name = "funboy-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
funboy-core = { path = "../funboy-core" }
fsl_interpreter = { version = "0.1.0", path = "../../fsl_interpreter" }
ollama-rs = "0.3.2"
async-recursion = "1.1.1"
tokio = {version = "1.39.2", features = ["full"]}
dotenvy = "0.15.7"
sqlx = "0.8.6"
rustyline = "18.0.0"
clap = { version = "4.5.0", features = ["derive"] }
